### PR TITLE
Fix compilation issues when compiling with clang 11

### PR DESCRIPTION
**Pull request by offset1313**
Tested and verified

### CODE REVIEW

**Comment by offset1313** [comment]
Tested and verified

**Comment by nE0sIghT** [comment]
Is it fixed in newer techpack?

**Comment by offset1313** [comment]
your current tree has these errors

**Comment by offset1313** [comment]
> Is it fixed in newer techpack?

nooooo , we have to fix it also on latest caf tag

**Comment by offset1313** [comment]
You can cherry-pick those if those errors popped up.
But they appear only on new compilers like clang 11

**Pull request closed without merging**
