### PR TITLE
audio: asoc : Don't pass endianess and mode as argument to pcm format…

### PR DESCRIPTION
**Pull request by offset1313**
… v3 function

Endianess and mode should not be passed as arguments to q6asm_media_format_block_pcm_format_support_v3  function
Hence following error has been fixed:
../techpack/audio/asoc/msm-compress-q6-v2.c:1046:6: error: too many arguments to function call, expected 8, have 10
                                        ASM_LITTLE_ENDIAN,
                                        ^~~~~~~~~~~~~~~~~~
../techpack/audio/include/dsp/q6asm-v2.h:111:27: note: expanded from macro 'ASM_LITTLE_ENDIAN'
#define ASM_LITTLE_ENDIAN 0
                          ^
../techpack/audio/include/dsp/q6asm-v2.h:510:5: note: 'q6asm_media_format_block_pcm_format_support_v3' declared here
int q6asm_media_format_block_pcm_format_support_v3(struct audio_client *ac,
    ^
1 error generated.

### CODE REVIEW

**Comment by nE0sIghT** [comment]
Hmm for some reason my working kernel do not have those errors.
Something messed in my branch.

**Comment by nE0sIghT** [comment]
Ahh I wrongly pushed techpack update to wip branch.
Will drop it for now.

**Comment by offset1313** [comment]
Or I should fix all

**Comment by offset1313** [comment]
Wait I am fixing all don't revert anything.

**Comment by offset1313** [comment]
Few more fixes included in pull now

**Comment by offset1313** [comment]
All fixed compiles fine

**Comment by nE0sIghT** [comment]
I dropped techpack update for now. See also https://github.com/nE0sIghT/android_kernel_xiaomi_msm8953/commit/735f32c4669ec088e9e440da0b5710c77d539089

**Pull request closed without merging**
