### PR TITLE
asoc: codecs: import missing Mido Specific change

### PR DESCRIPTION
**Pull request by offset1313**
referenced from https://github.com/MiCode/Xiaomi_Kernel_OpenSource/commit/e12ec432a9ef867a3602a8e63322bc6b7aabcfd2

### CODE REVIEW

**Comment by offset1313** [comment]
This code block shouldn't be ignored on mido .

**Comment by nE0sIghT** [comment]
Thanks.
I think this can fix FM radio issue - I will check it

**Comment by nE0sIghT** [comment]
Merged as c3d54010394f6c2270f97d4680305502a0560c41

**Comment by Nicklas373** [comment]
Good then, Will merged this too

**Pull request merged**
